### PR TITLE
Add result entity

### PR DESCRIPTION
**Pull request by Lesekater**
## Proposed change

Adds an additional entity to look at the last result and also save a history of which Agent was used to execute a intent:

grafik

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New integration (thank you!)
- [x] New feature (which adds functionality to an existing integration)
- [ ] Deprecation (breaking change to happen in the future)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: 
- Link to documentation pull request: 

## Checklist

- [x] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] I have followed the [perfect PR recommendations][perfect-pr]
- [ ] The code has been formatted using Ruff (`ruff format homeassistant tests`)
- [ ] Tests have been added to verify that the new code works.

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[manifest-docs]: https://developers.home-assistant.io/docs/creating_integration_manifest/
[quality-scale]: https://developers.home-assistant.io/docs/integration_quality_scale_index/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

**Comment by m50** [comment]
Before you mark this ready for review, could you please provide a use case for this? That way I may understand better why it would be helpful. I think I have an idea, but it would be good to know for sure.

**Comment by Lesekater** [comment]
Sure, it's mainly an alternative to the "debug" option. It helps you see which agent responded in the past without having Low Debug or Verbose Debug enabled and adding extra information to the speech response. 
Right now, I'm also experimenting with adding more details to the existing debug trace of HA conversations, which might be cleaner than creating an additional entity.

**Comment by Lesekater** [comment]
> Sure, it's mainly an alternative to the "debug" option. It helps you see which agent responded in the past without having Low Debug or Verbose Debug enabled and adding extra information to the speech response. Right now, I'm also experimenting with adding more details to the existing debug trace of HA conversations, which might be cleaner than creating an additional entity.

For me, having an additional debug history like this would be useful to see which commands are used throughout the day. Then, I could find commands currently handled by an LLM agent that could be replaced by simple automations with sentence triggers and handled locally.

**Comment by maxi1134** [comment]
> For me, having an additional debug history like this would be useful to see which commands are used throughout the day. Then, I could find commands currently handled by an LLM agent that could be replaced by simple automations with sentence triggers and handled locally.

This is a great idea!

**Comment by Lesekater** [comment]
Okay, it seems to work quite good now. I added formatting to the state so it can easily be used with a logbook card:
grafik

the rest of the information is still written to the attributes, but sadly i didn't found a clean way to show the attribute history in lovelance so i think writing a bit more information into the state is the cleanest way.
grafik

**Comment by m50** [comment]
> > Sure, it's mainly an alternative to the "debug" option. It helps you see which agent responded in the past without having Low Debug or Verbose Debug enabled and adding extra information to the speech response. Right now, I'm also experimenting with adding more details to the existing debug trace of HA conversations, which might be cleaner than creating an additional entity.
> 
> For me, having an additional debug history like this would be useful to see which commands are used throughout the day. Then, I could find commands currently handled by an LLM agent that could be replaced by simple automations with sentence triggers and handled locally.

This sounds great, for sure, and completely within scope of this. Much appreciated.

I will add, you can get some additional information (i.e., what responded with the response) from the intent information in the Voice Assistant Debug area:

```
intent:
  engine: conversation.fallback_conversation_agent
  language: en
  intent_input: What time is it?
  conversation_id: null
  device_id: null
  done: true
  intent_output:
    response:
      speech:
        plain:
          speech: 4:41 PM
          extra_data: null
          original_speech: 4:41 PM
          agent_name: Home Assistant
          agent_id: conversation.home_assistant
```

You see under the `intent_output` section, it shows the agent name and agent ID of what generated the response.

However, your implementation definitely adds more information.

I just got back from vacation where I had no computer, I'll be reviewing this in the next couple of days.

**Review by m50 — APPROVED** [review]

**Pull request merged**
